osx_image: xcode9.2
language: objective-c
xcode_project: GroupWork.xcodeproj

script:
  - swift build
  - swift test
  
notifications:
  email:
    recipients:
      - qvo1987@gmail.com
    on_success: always
    